In [1]:
import numpy as np

In [3]:
array_original = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
array_original

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
array_view = array_original[1:, 1:]
array_view

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [6]:
array_view[0, 0] = 99
array_view

array([[99,  8,  9, 10],
       [12, 13, 14, 15]])

In [7]:
array_original

array([[ 1,  2,  3,  4,  5],
       [ 6, 99,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
#copia profunda

array_copy = array_original.copy()
array_copy

array([[ 1,  2,  3,  4,  5],
       [ 6, 99,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
array_copy[0, 0] = 100
array_copy

array([[100,   2,   3,   4,   5],
       [  6,  99,   8,   9,  10],
       [ 11,  12,  13,  14,  15]])