In [1]:
import numpy as np

In [2]:
array =  np.array([[1, 2, 3, 4, 5,], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])

array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
fatiando_linhas = array[1:4, 1:4]

print(fatiando_linhas)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [6]:
fatiando_colunas = array[:, 0:3]

print(fatiando_colunas)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]


In [8]:
sub_array = array[1:4, 1:4]
print(sub_array)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
