In [1]:
import numpy as np

In [7]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#adição de uma nova linha
soma = np.add(array, 10)
soma

sub = np.subtract(array, 2)
sub

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [8]:
prod = np.multiply(array, 2)
prod

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [9]:
div = np.divide(array, 2)
div

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])