In [1]:
import numpy as np

In [2]:
np.__version__

'2.5.3'

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [10]:
soma = arr + 20
multiplicacao = arr * 2
media = arr.mean()

In [11]:
print(soma)
print(multiplicacao)
print(media)

[21 22 23 24 25]
[ 2  4  6  8 10]
3.0
